version: '3.7'
services:
    client:
        build:
          context: ./client
          dockerfile: ./Dockerfile
        restart: always
        ports:
            - 3000:3000
            - 9229:9229
        volumes:
            - /client:/usr/src/app
            - /client/node_modules
        working_dir: /usr/src/app
        command: npm start
        links:
            - api
        networks:
            - sparkwebappnetwork
    api:
        build:
          context: ./api
          dockerfile: ./Dockerfile
        restart: always
        ports:
            - 3001:3001
        volumes:
            - /api:/usr/src/app
            - /api/node_modules
        working_dir: /usr/src/app
        command: npm start
        depends_on:
            - mongodb
        networks:
            - sparkwebappnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth --smallfiles
        networks:
            - sparkwebappnetwork

networks:
    sparkwebappnetwork:
        driver: bridge
