version: "3"
services:
    client:
        image: node:11.10.0-alpine
        restart: always
        ports:
            - "3080:3080"
        volumes:
            - ./client:/client
            - /client/node_modules
        entrypoint: ["npm", "start"]
        links:
            - api
        networks:
            - sparkwebappnetwork
    api:
        image: node:11.10.0-alpine
        restart: always
        ports:
            - "9080:9080"
        volumes:
            - ./api:/api
            - /api/node_modules
        entrypoint: ["npm", "start"]
        depends_on:
            - mongodb
        networks:
            - sparkwebappnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth --smallfiles
        networks:
            - sparkwebappnetwork
networks:
    sparkwebappnetwork:
        driver: bridge
