version: '3.7'
services:
    client:
        build:
          context: ./client
          dockerfile: Dockerfile
        restart: always
        ports:
            - 3000:3000
            - 9229:9229
        volumes:
            - .:/client
            - /client/node_modules
        command: npm start
        links:
            - api
        networks:
            - sparkwebappnetwork
    api:
        build:
          context: ./api
          dockerfile: Dockerfile
        restart: always
        ports:
            - 3001:3001
        volumes:
            - .:/api
            - /api/node_modules
        command: npm run dev
        depends_on:
            - mongodb
        networks:
            - sparkwebappnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth --smallfiles
        networks:
            - sparkwebappnetwork

    mongo-express:
        image: mongo-express
        ports:
          - 8081:8081
        networks:
            - sparkwebappnetwork

networks:
    sparkwebappnetwork:
        driver: bridge
